### ISSUE TITLE
Read Keptn API credentials from k8s secrets

### ISSUE THREAD

**Issue by laszlocph** [keptn-sandbox/onechart-service#16]
Since the services are deployed in the same namespace, these can be mounted:

```
env:
  - name: CONFIGURATION_SERVICE
    value: 'http://172.21.0.2.nip.io/api' # output of `http://$(kubectl -n keptn get ingress api-keptn-ingress -ojsonpath='{.spec.rules[0].host}')/api`
  - name: API_TOKEN
    value: "xx" # output of `kubectl get secret keptn-api-token -n keptn -ojsonpath='{.data.keptn-api-token}' | base64 --decode`
```
